openapi: 3.2.0
info:
  title: Fundrise Connect (External API) Offerings API
  version: 1.0.0
  contact:
    name: Fundrise Connect Support Team
    email: connect@fundrise.com
  description: '### Introduction

    Fundrise is a Fintech company democratizing access to alternative assets through technology.'
  x-logo:
    url: https://d10cq78zmnjvsx.cloudfront.net/interface/logo-hz-color.svg
    backgroundColor: '#FFFFFF'
    altText: Fundrise
    href: .
servers:
- description: Sandbox
  url: https://sandbox.fundrise.com
tags:
- name: Offerings
  description: The Offerings API contains information about all Offerings available via Fundrise Connect and documents associated with those offerings.
paths:
  /v1/offerings:
    get:
      description: Returns a list of Fundrise Offerings accessible via this API. This endpoint supports a query parameter to filter Offerings for a specific asset class. Not passing the query parameter will return all available asset classes.
      operationId: GetOfferings
      parameters:
      - $ref: '#/components/parameters/AssetClassQuery'
      security:
      - PartnerBasicAuthentication: []
      summary: Get Offerings
      tags:
      - Offerings
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferingResponse'
              example:
              - offeringId: '1'
                currentPrice:
                  price: '10.0'
                  priceDate: '2020-01-01T00:00:00Z'
                offeringName: Income Interval Fund
                status: OPEN
                assetClass:
                  assetClassType: PRIVATE_CREDIT
                  assetClassLabel: Private Credit
                minimumInvestmentAmount: '10.00'
                maximumInvestmentAmount: '100000.00'
                primaryObjective: Cash flow
                currentDistributionRate: '.41'
              - offeringId: '2'
                offeringName: Flagship Real Estate Fund
                status: OPEN
                assetClass:
                  assetClassType: REAL_ESTATE
                  assetClassLabel: Real Estate
                minimumInvestmentAmount: '10.00'
                maximumInvestmentAmount: '100000.00'
                primaryObjective: Appreciation
                currentDistributionRate: '.41'
              - offeringId: '3'
                offeringName: Innovation Fund
                status: CLOSED
                assetClass:
                  assetClassType: VENTURE
                  assetClassLabel: Venture
                minimumInvestmentAmount: '10.00'
                maximumInvestmentAmount: '100000.00'
                primaryObjective: Appreciation
                currentDistributionRate: '.41'
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
  /v1/offering/{offeringId}/nav:
    get:
      description: Returns the historical daily net asset values for a Fundrise Offering accessible via this API.
      operationId: GetHistoricalNav
      parameters:
      - $ref: '#/components/parameters/OfferingIdPath'
      security:
      - PartnerBasicAuthentication: []
      summary: Get Historical Daily NAV
      tags:
      - Offerings
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferingHistoricalNavResponse'
              example:
                offeringId: '24'
                historicalDailyNav:
                - effectiveDate: '2023-01-02T00:00:00Z'
                  netAssetValuePerShare: '10.03'
                - effectiveDate: '2023-01-01T00:00:00Z'
                  netAssetValuePerShare: '10.02'
        '401':
          $ref: '#/components/responses/401'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FundriseConnectError'
              examples:
                LiquidationNotFound:
                  value:
                    referenceId: ed8583b9-6cd9-43ed-ad46-c7c52fff0c34
                    code: '200101'
                    message: Invalid offeringId provided
        '500':
          $ref: '#/components/responses/500'
  /v1/offering/{offeringId}/documents:
    get:
      description: The documents API provides access to Fundrise Offering documentation to place Investments. When a user has selected what Offering they would like to invest in from the `GET /v1/offerings` endpoint, the documents (typically a `SUBSCRIPTION_AGREEMENT` and `PROSPECTUS` or `OFFERING_CIRCULAR`) need to be displayed to the user before investing into the Offering.
      operationId: GetOfferingDocuments
      security:
      - PartnerBasicAuthentication: []
      summary: Get Offering Documents
      tags:
      - Offerings
      parameters:
      - $ref: '#/components/parameters/OfferingIdPath'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentResponse'
              examples:
                investment-docs:
                  value:
                  - documentId: '1'
                    documentName: Fundrise Equity eREIT Offering Circular (December 2022) Supp 1.pdf
                    documentType: OFFERING_CIRCULAR
                    documentUrl: https://d10cq78zmnjvsx.cloudfront.net/website-documents/a1b48469-6cab-4965-ad24-fcde28037d31/Fundrise%20Equity%20eREIT%20Offering%20Circular%20(December%202022)%20Supp%201.pdf
                  - documentId: '2'
                    documentName: Fundrise Equity eREIT Subscription Agreement (December 2022) - final.pdf
                    documentType: AGREEMENT
                    documentUrl: https://d10cq78zmnjvsx.cloudfront.net/reit-documents/45eee3fb-d77c-4804-aca2-f0c96e413e02/Fundrise%20Equity%20eREIT%20Subscription%20Agreement%20(December%202022)%20-%20final.pdf
        '401':
          $ref: '#/components/responses/401'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FundriseConnectError'
              examples:
                LiquidationNotFound:
                  value:
                    referenceId: ed8583b9-6cd9-43ed-ad46-c7c52fff0c34
                    code: '200102'
                    message: Documents not found for provided offeringId
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    Identifier:
      title: Identifier
      description: Value for a unique identifier.
      type: string
      format: int64
    DocumentResponse:
      title: Document
      description: A Fundrise Document.
      type: object
      properties:
        documentId:
          description: The unique Document ID.
          type: string
          format: int64
        documentName:
          maxLength: 2000
          type: string
        documentType:
          $ref: '#/components/schemas/DocumentTypeEnum'
        documentUrl:
          maxLength: 2000
          type: string
    OfferingStatusEnum:
      title: Offering Status
      description: The current status of the offering. `OPEN` indicates the Offering can be invested in while `CLOSED` indicates the Offering is unavailable.
      maxLength: 256
      enum:
      - OPEN
      - CLOSED
    AssetClassEnum:
      title: Asset Class type
      description: The asset class of the offering.
      maxLength: 256
      enum:
      - REAL_ESTATE
      - PRIVATE_CREDIT
      - VENTURE
    AssetClass:
      title: Asset Class
      description: The asset class of the offering.
      type: object
      properties:
        assetClassType:
          $ref: '#/components/schemas/AssetClassEnum'
        assetClassLabel:
          type: string
          description: Human readable label for the asset class
    StringArray:
      type: array
      items:
        type: string
    OfferingNavResponse:
      title: Offering NAV Response
      description: A historical daily NAV entry
      properties:
        effectiveDate:
          description: The date the NAV was effective.
          type: string
          format: date-time
        netAssetValuePerShare:
          description: The share value.
          type: string
          format: double
    DocumentTypeEnum:
      title: Document Type
      description: Enum representing the document type.
      maxLength: 256
      enum:
      - AGREEMENT
      - ACKNOWLEDGMENT
      - DISCLOSURE
      - PROSPECTUS
      - OFFERING_CIRCULAR
      - OTHER
      - STATEMENT
      - TAX_FORM
    PriceResponse:
      title: Price Response
      description: A Fundrise Offering Price.
      type: object
      properties:
        price:
          description: The Offering Price.
          type: string
          format: double
        priceDate:
          description: The effective date-time of the price.
          type: string
          format: date-time
    FieldErrorMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/StringArray'
    OfferingResponse:
      title: Offering Response
      description: A Fundrise Offering.
      type: object
      properties:
        currentPrice:
          anyOf:
          - type: 'null'
          - $ref: '#/components/schemas/PriceResponse'
        offeringId:
          description: The Offering ID
          $ref: '#/components/schemas/Identifier'
        offeringName:
          description: The Offering name.
          maxLength: 2000
          type: string
        status:
          $ref: '#/components/schemas/OfferingStatusEnum'
        assetClass:
          $ref: '#/components/schemas/AssetClass'
        minimumInvestmentAmount:
          description: The minimum amount that can be invested into the fund in USD.
          type: string
          format: double
        maximumInvestmentAmount:
          description: The maximum amount that can be invested into the fund in USD.
          type: string
          format: double
        primaryObjective:
          description: The main goal of the fund.
          type: string
          maxLength: 256
        currentDistributionRate:
          description: The current distribution rate of the fund. This represents the approximate annualized dividend percentage of the fund.
          type: string
          format: double
      required:
      - offeringId
      - offeringName
      - status
      - assetClass
      - minimumInvestmentAmount
      - maximumInvestmentAmount
      - primaryObjective
      - currentDistributionRate
    OfferingHistoricalNavResponse:
      title: Offering NAV Response
      description: Historical Daily NAV for a Fundrise Offering.
      type: object
      properties:
        offeringId:
          description: The Offering ID
          $ref: '#/components/schemas/Identifier'
        historicalDailyNav:
          type: array
          description: The historical daily net asset values of the fund in USD.
          items:
            $ref: '#/components/schemas/OfferingNavResponse'
      required:
      - offeringId
      - historicalDailyNav
    FundriseConnectError:
      title: Error object
      description: Error from Fundrise Connect.
      type: object
      properties:
        referenceId:
          description: A unique reference ID generated for every request that is for error tracing.
          maxLength: 1000
          type: string
        code:
          description: A numeric code mapping to a specific validation error.
          maxLength: 6
          type: string
        message:
          description: A human readable description of the error.
          maxLength: 1000
          type: string
        validationErrors:
          description: A map of field names to an array of form validation error messages
          $ref: '#/components/schemas/FieldErrorMap'
      required:
      - referenceId
  parameters:
    OfferingIdPath:
      name: offeringId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Identifier'
        description: The Offering ID (returned by the <a href="#tag/Offerings/operation/GetOfferings">Get Offerings</a> operation) associated with the request.
    AssetClassQuery:
      name: assetClass
      in: query
      description: Enum indicating the underlying asset class that the Offering represents.
      required: false
      schema:
        $ref: '#/components/schemas/AssetClassEnum'
  responses:
    '401':
      description: Unauthorized request to server, Invalid access token or Partner credentials
    '500':
      description: Internal Service Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FundriseConnectError'
          examples:
            clientExists:
              value:
                referenceId: ed8583b9-6cd9-43ed-ad46-c7c52fff0c35
                message: Internal service error
  securitySchemes:
    PartnerBasicAuthentication:
      description: PartnerBasicAuthentication is enforced by HTTP Basic Authentication. A Partner username and password will be provided by Fundrise support.  The Partner password should be stored securely. At a minimum, it should be encrypted at-rest and access restricted to services making requests to the Fundrise API. The Partner password should not be exposed to a Client or any of their devices. If the password is compromised please contact Fundrise support.
      type: http
      scheme: basic
    ClientBearerAuthentication:
      description: 'ClientBearerAuthentication is enforced by HTTP Bearer Authentication and requires an OAuth access token.  Since access tokens are scoped to specific Clients, they identify and authenticate the Client in a request.


        Access tokens can be obtained in <a href="#tag/Authentication/operation/GetAccessToken">Get Access Token</a> requests by using the refresh token flow. OAuth refresh token are issued on <a href="#tag/Clients/operation/CreateClient">Client Creation</a> and scoped specifically to that Client. The refresh tokens will not expire and should be stored securely after Client creation. At a minimum, refresh tokens should be encrypted at-rest and access restricted to services making requests to the Fundrise API. Refresh tokens should not be exposed to a Client or any of their devices.'
      type: http
      scheme: bearer
